version: "3.9"

services:
  site_dev:
    build:
      context: ../clients/site
      dockerfile: Dockerfile.dev
    container_name: site_dev
    ports:
      - "5174:5174"
    volumes:
      - ../clients/site:/app
      - site_node_modules:/app/node_modules
    working_dir: /app

  admin_dev:
    build:
      context: ../clients/admin
      dockerfile: Dockerfile.dev
    container_name: admin_dev
    ports:
      - "5173:5173"
    volumes:
      - ../clients/admin:/app
      - admin_node_modules:/app/node_modules
    working_dir: /app

volumes:
  site_node_modules:
  admin_node_modules:
